<a href="https://colab.research.google.com/github/Princekumarmehta/Machine_learning_lab/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
list=[1,2,3,4]
a=np.array(list)
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4]


In [ ]:
list1=[[1,2,3,4],[3,4,5,6]]
p=np.array(list1)

In [ ]:
p

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [ ]:
a=np.add(5,4)
a

9

In [ ]:
a=np.zeros((4,5),dtype=int)
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
x=np.ones((3,4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
x=np.full((4,5),8)

In [ ]:
x

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [ ]:
# create a numpy array with random values
b = np.random.randint(10,15,(3,4))
print(b)

[[11 12 13 11]
 [12 10 10 12]
 [14 13 12 12]]


In [ ]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.96141423 0.38363762 0.53033709 0.65717312]
 [0.89287062 0.86300473 0.24744512 0.85984372]
 [0.84555234 0.84593172 0.68421799 0.19542655]]


In [ ]:
n=20
p=4
q=5
ar=np.arange(n).reshape(p,q)
ar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
n=25
p=5
q=5
ar=np.arange(n).reshape(p,q)
ar


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ar[4]=[5,6,7,8,9]

In [ ]:
ar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9]])

In [ ]:
ar=np.random.randint(10,40,(4,5))
ar

array([[25, 35, 15, 11, 32],
       [12, 12, 21, 25, 10],
       [27, 27, 37, 32, 26],
       [35, 26, 25, 17, 19]])

In [ ]:
ar=np.random.random((4,5))
ar

array([[0.60242068, 0.26316507, 0.65398863, 0.77628193, 0.58914959],
       [0.98534918, 0.0545028 , 0.95893664, 0.20080204, 0.68980207],
       [0.01924745, 0.2394758 , 0.66258266, 0.24318433, 0.90767742],
       [0.83982934, 0.9199112 , 0.10876887, 0.26182347, 0.88999603]])

In [ ]:
rows = int(input("Enter the number of rows: "))
cols = int(input("Enter the number of columns: "))

input_list = []

for i in range(rows):
    lister=[]
    for j in range(cols):
       lister.append(int(input("Enter the value")))
    input_list.append(lister)

array_2d = np.array(input_list)

print("2D Array:")
print(array_2d)

Enter the number of rows: 2
Enter the number of columns: 2
Enter the value1
Enter the value2
Enter the value3
Enter the value4
2D Array:6
[[1 2]
 [3 4]]


In [ ]:
a=np.random.randint(10,30,(3,3))
b=np.random.randint(10,30,(3,3))
a


array([[23, 15, 13],
       [16, 11, 10],
       [22, 13, 24]])

In [ ]:
b

array([[29, 15, 22],
       [12, 16, 15],
       [20, 12, 28]])

In [ ]:
p=np.mod(a,b)
p

array([[23,  0, 13],
       [ 4, 11, 10],
       [ 2,  1, 24]])

In [ ]:
a[0]=[23,23,23]
print(a)
print(np.unique(a))
print(a)

[[23 23 23]
 [16 11 10]
 [22 13 24]]
[10 11 13 16 22 23 24]
[[23 23 23]
 [16 11 10]
 [22 13 24]]
